spring:
  profiles:
    active: local
  session:
    store-type: redis

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

wait:
  queue:
    pass-chunk-size: 150
---
spring:
  config:
    activate:
      on-profile: local

  data:
    redis:
      host: localhost
      port: 6379
      password: ""

server:
  port: 8081
---
spring:
  config:
    activate:
      on-profile: docker

  data:
    redis:
      host: redis
      port: 6379
      password: ""
---
spring:
  config:
    activate:
      on-profile: prod

logging:
  level:
    org.hibernate.SQL: debug
