spring:
  profiles:
    active: local

  session:
    store-type: redis

  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 50 # ?? ??? ? ????? ??
      minimum-idle: 50 # ?? idle ??? ? ????? ??

  data:
    redis:
      host: localhost
      port: 6379
      password: ""

  task:
    execution:
      pool:
        core-size: 75
        max-size: 200
        queue-capacity: 10000

logging:
  level:
    org.hibernate.SQL: off
    com.wootecam.festivals: debug
    org.hibernate.engine.internal.StatisticalLoggingSessionEventListener: off

server:
  port: 8082
  tomcat:
    threads:
      min-spare: 75
      max: 75
      max-queue-capacity: 10000

---
spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:mysql://mysql:3306/twodari?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password:

  data:
    redis:
      host: localhost
      port: 6379
      password: ""

server:
  port: 8082
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${secret-datasource.url}
    username: ${secret-datasource.username}
    password: ${secret-datasource.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 20
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        generate_statistics: true
  data:
    redis:
      host: ${secret-redis.host}
      port: ${secret-redis.port}
      password: ${secret-redis.password}
    task:
      execution:
        pool:
          core-size: 15
          max-size: 50
          queue-capacity: 2000

logging:
  level:
    org.hibernate.SQL: off
    com.wootecam.festivals: error
    org.hibernate.engine.internal.StatisticalLoggingSessionEventListener: off

---
spring:
  config:
    activate:
      on-profile: docker

  datasource:
    url: jdbc:mysql://mysql:3306/twodari?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password:

  data:
    redis:
#      host: redis
      host: localhost
      port: 6379
      password: ""

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
        generate_statistics: true

logging:
  level:
    com.wootecam.festivals: debug