spring:
  profiles:
    active: local
  session:
    store-type: redis

  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 50 # 최대 커넥션 수 커스텀하게 사용
      minimum-idle: 50 # 최소 idle 커넥션 수 커스텀하게 사용
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        default_schema: twodari

  quartz:
    scheduler-name: quartzScheduler
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
    properties:
      org.quartz:
        scheduler:
          instanceName: FestivalScheduler
          instanceId: AUTO
        jobStore:
          class: org.quartz.impl.jdbcjobstore.JobStoreTX
          driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
          useProperties: false
          dataSource: schedule
          isClustered: true
          misfireThreshold: 30000
          clusterCheckinInterval: 10000
          tablePrefix: QRTZ_ # Quartz 테이블 이름 접두사
        dataSource:
          schedule:
            driver: com.mysql.cj.jdbc.Driver
            URL: ${QUARTZ_DATASOURCE_URL}
            user: ${QUARTZ_DATASOURCE_USERNAME}
            password: ${QUARTZ_DATASOURCE_PASSWORD}
            maxConnections: 5
            provider: hikaricp


  data:
    redis:
      host: localhost
      port: 6379
      password: ""

logging:
  level:
    org.hibernate.SQL: off
    com.wootecam.festivals: warn
    org.hibernate.engine.internal.StatisticalLoggingSessionEventListener: off
    org.springframework.scheduling.quartz: debug

management:
  endpoints:
    web:
      exposure:
        include: "*"
  prometheus:
    metrics:
      export:
        enabled: true

---
spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:mysql://localhost:3306/twodari?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password:

  quartz:
    properties:
      org.quartz:
        dataSource:
          schedule:
            driver: com.mysql.cj.jdbc.Driver
            URL: jdbc:mysql://localhost:3306/schedule?useSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
            user: root
            password:
            maxConnections: 5
            provider: hikaricp
---
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: ${secret-datasource.url}
    username: ${secret-datasource.username}
    password: ${secret-datasource.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 20
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        generate_statistics: true

  data:
    redis:
      host: ${secret-redis.host}
      port: ${secret-redis.port}
      password: ${secret-redis.password}
    task:
      execution:
        pool:
          core-size: 15
          max-size: 50
          queue-capacity: 2000

  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: never

logging:
  level:
    org.hibernate.SQL: off
    com.wootecam.festivals: error
    org.hibernate.engine.internal.StatisticalLoggingSessionEventListener: off

---
spring:
  config:
    activate:
      on-profile: docker

  datasource:
    url: jdbc:mysql://mysql:3306/twodari?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password:

  data:
    redis:
      host: redis
      port: 6379
      password: ""

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
        generate_statistics: true

  quartz:
    scheduler-name: quartzScheduler
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
    properties:
      org.quartz:
        scheduler:
          instanceName: FestivalScheduler
          instanceId: AUTO
        jobStore:
          class: org.quartz.impl.jdbcjobstore.JobStoreTX
          driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
          useProperties: false
          dataSource: schedule
          isClustered: true
          misfireThreshold: 10000
          clusterCheckinInterval: 5000
          tablePrefix: QRTZ_ # Quartz 테이블 이름 접두사
        dataSource:
          schedule:
            driver: com.mysql.cj.jdbc.Driver
            URL: jdbc:mysql://mysql:3306/schedule?useSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
            user: root
            password:
            maxConnections: 5
            provider: hikaricp

logging:
  level:
    com.wootecam.festivals: debug
